# Generated by Django 5.0.1 on 2024-02-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0003_alter_userimage_face_encoding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to='face_recognition_app/media/'),
        ),
    ]
