# Generated by Django 5.0.1 on 2024-02-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0004_alter_userimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='face_encoding',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='face_locations',
            field=models.TextField(),
        ),
    ]
