# Generated by Django 5.0.1 on 2024-02-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition_app', '0005_alter_userimage_face_encoding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
